/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// biome-ignore-all lint: TanStack Router が生成する

// biome-ignore-all format: TanStack Router が生成する

// biome-ignore-all assist: TanStack Router が生成する

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MtgRouteImport } from './routes/mtg'
import { Route as SessionsRouteImport } from './routes/sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MtgRoute = MtgRouteImport.update({
  id: '/mtg',
  path: '/mtg',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mtg': typeof MtgRoute
  '/sessions': typeof SessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mtg': typeof MtgRoute
  '/sessions': typeof SessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mtg': typeof MtgRoute
  '/sessions': typeof SessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mtg' | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mtg' | '/sessions'
  id: '__root__' | '/' | '/mtg' | '/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MtgRoute: typeof MtgRoute
  SessionsRoute: typeof SessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtg': {
      id: '/mtg'
      path: '/mtg'
      fullPath: '/mtg'
      preLoaderRoute: typeof MtgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MtgRoute: MtgRoute,
  SessionsRoute: SessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
