/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MtgRouteImport } from './routes/mtg'
import { Route as NowRouteImport } from './routes/now'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordsIdRouteImport } from './routes/records.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MtgRoute = MtgRouteImport.update({
  id: '/mtg',
  path: '/mtg',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mtg': typeof MtgRoute
  '/now': typeof NowRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/records/$id': typeof RecordsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mtg': typeof MtgRoute
  '/now': typeof NowRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/records/$id': typeof RecordsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mtg': typeof MtgRoute
  '/now': typeof NowRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/records/$id': typeof RecordsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mtg' | '/now' | '/search' | '/settings' | '/records/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mtg' | '/now' | '/search' | '/settings' | '/records/$id'
  id:
    | '__root__'
    | '/'
    | '/mtg'
    | '/now'
    | '/search'
    | '/settings'
    | '/records/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MtgRoute: typeof MtgRoute
  NowRoute: typeof NowRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  RecordsIdRoute: typeof RecordsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtg': {
      id: '/mtg'
      path: '/mtg'
      fullPath: '/mtg'
      preLoaderRoute: typeof MtgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MtgRoute: MtgRoute,
  NowRoute: NowRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  RecordsIdRoute: RecordsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
