/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdviceRouteImport } from './routes/advice'
import { Route as MtgRouteImport } from './routes/mtg'
import { Route as NowRouteImport } from './routes/now'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RecordsIdRouteImport } from './routes/records.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceRoute = AdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => rootRouteImport,
} as any)
const MtgRoute = MtgRouteImport.update({
  id: '/mtg',
  path: '/mtg',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/mtg': typeof MtgRoute
  '/now': typeof NowRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/mtg': typeof MtgRoute
  '/now': typeof NowRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/mtg': typeof MtgRoute
  '/now': typeof NowRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/records/$id': typeof RecordsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advice'
    | '/mtg'
    | '/now'
    | '/people'
    | '/projects'
    | '/search'
    | '/terms'
    | '/records/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advice'
    | '/mtg'
    | '/now'
    | '/people'
    | '/projects'
    | '/search'
    | '/terms'
    | '/records/$id'
  id:
    | '__root__'
    | '/'
    | '/advice'
    | '/mtg'
    | '/now'
    | '/people'
    | '/projects'
    | '/search'
    | '/terms'
    | '/records/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdviceRoute: typeof AdviceRoute
  MtgRoute: typeof MtgRoute
  NowRoute: typeof NowRoute
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  RecordsIdRoute: typeof RecordsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice': {
      id: '/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof AdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtg': {
      id: '/mtg'
      path: '/mtg'
      fullPath: '/mtg'
      preLoaderRoute: typeof MtgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdviceRoute: AdviceRoute,
  MtgRoute: MtgRoute,
  NowRoute: NowRoute,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  RecordsIdRoute: RecordsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
