/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CaptureConversation {
  branch: string | null;
  external_id: string | null;
  id: string | null;
  origin: string | null;
  project_id: number | null;
  started_at: string | null;
}

export interface CaptureMessage {
  body: string | null;
  content_hash: Buffer | null;
  conversation_id: string | null;
  external_id: string | null;
  id: string | null;
  indexed: number | null;
  original_bytes: number | null;
  sent_at: string | null;
  speaker_kind: string | null;
  truncated: number | null;
  turn_id: string | null;
}

export interface CaptureMessageFile {
  action: string | null;
  message_id: string | null;
  path: string | null;
}

export interface Conversation {
  branch: string | null;
  external_id: string;
  id: string;
  origin: string;
  project_id: number;
  started_at: string;
}

export interface Knowledge {
  body: string;
  command: string | null;
  confidence: string | null;
  confirmation: string | null;
  content_hash: Buffer;
  conversation_id: string | null;
  decision_id: number | null;
  downsides: ColumnType<string[], string | undefined, string>;
  heading: string | null;
  id: Generated<number>;
  kind: string;
  occurred_at: string;
  project_id: number;
  pull_request_id: number | null;
  reason: string | null;
  refs: ColumnType<string[], string | undefined, string>;
  source_key: string;
  status: string | null;
  superseded_by_id: number | null;
  work_item_id: number | null;
}

export interface KnowledgeFile {
  knowledge_id: number;
  line_end: number | null;
  line_start: number | null;
  path: string;
  role: string;
}

export interface KnowledgeSearchText {
  b: string | null;
  e: string | null;
  h: string | null;
  id: number | null;
}

export interface KnowledgeTerms {
  content_hash: Buffer;
  knowledge_id: Generated<number>;
  source: string;
  terms: string;
  written_at: string;
}

export interface Message {
  body: string;
  content_hash: Buffer;
  conversation_id: string;
  external_id: string;
  id: string;
  indexed: number;
  original_bytes: number;
  sent_at: string;
  seq: Generated<number>;
  speaker_kind: string;
  truncated: Generated<number>;
  turn_id: string | null;
}

export interface MessageFile {
  action: string;
  line_end: number | null;
  line_start: number | null;
  message_id: string;
  path: string;
}

export interface Project {
  created_at: Generated<string>;
  id: Generated<number>;
  key: string;
  name: string;
}

export interface PullRequest {
  github_id: number | null;
  harvested_at: string | null;
  id: Generated<number>;
  number: number;
  project_id: number;
  state: string;
  title: string;
  url: string | null;
}

export interface WorkItem {
  conversation_id: string | null;
  current: string;
  goal: string;
  id: Generated<number>;
  next: ColumnType<string[], string | undefined, string>;
  project_id: number;
  source_key: string;
  status: string;
  title: string;
  updated_at: string;
}

export interface DB {
  capture_conversation: CaptureConversation;
  capture_message: CaptureMessage;
  capture_message_file: CaptureMessageFile;
  conversation: Conversation;
  knowledge: Knowledge;
  knowledge_file: KnowledgeFile;
  knowledge_search_text: KnowledgeSearchText;
  knowledge_terms: KnowledgeTerms;
  message: Message;
  message_file: MessageFile;
  project: Project;
  pull_request: PullRequest;
  work_item: WorkItem;
}
