/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface GleaneryConnector {
  head_oid: string | null;
  id: Generated<Int8>;
  last_error: string | null;
  last_success_at: Timestamp | null;
  project_id: Int8;
  provider: string;
  snapshot_at: Timestamp | null;
}

export interface GleaneryConversation {
  branch: string | null;
  external_id: string;
  id: string;
  origin: string;
  project_id: Int8;
  source_item_id: Int8 | null;
  started_at: Timestamp;
  title: string | null;
}

export interface GleaneryDocsExclude {
  connector_id: Int8;
  kind: string;
  path: string;
}

export interface GleaneryKnowledge {
  body: string;
  command: string | null;
  confidence: string | null;
  confirmation: string | null;
  content_hash: Buffer;
  conversation_id: string | null;
  decision_id: Int8 | null;
  downsides: Generated<string[]>;
  heading: string | null;
  id: Generated<Int8>;
  kind: string;
  lexemes: string;
  occurred_at: Timestamp;
  project_id: Int8;
  reason: string | null;
  refs: Generated<string[]>;
  source_item_id: Int8 | null;
  source_key: string;
  stance: Generated<string>;
  status: string | null;
  superseded_by_id: Int8 | null;
  work_item_id: Int8 | null;
}

export interface GleaneryKnowledgeEmbedding {
  attempts: Generated<number>;
  embedding: string | null;
  knowledge_id: Int8;
  last_error: string | null;
  model: string;
  source_hash: Buffer;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface GleaneryKnowledgeFile {
  knowledge_id: Int8;
  line_end: number | null;
  line_start: number | null;
  path: string;
  role: string;
}

export interface GleaneryMessage {
  body: string;
  content_hash: Buffer;
  conversation_id: string;
  external_id: string;
  id: string;
  identity_id: Int8 | null;
  lexemes: string | null;
  original_bytes: number;
  reply_to_id: string | null;
  sent_at: Timestamp;
  speaker_kind: string;
  truncated: Generated<boolean>;
  turn_id: string | null;
  url: string | null;
}

export interface GleaneryMessageEmbedding {
  attempts: Generated<number>;
  embedding: string | null;
  last_error: string | null;
  message_id: string;
  model: string;
  source_hash: Buffer;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface GleaneryMessageFile {
  action: string;
  line_end: number | null;
  line_start: number | null;
  message_id: string;
  path: string;
}

export interface GleaneryPerson {
  display_name: string;
  id: Generated<Int8>;
  is_self: Generated<boolean>;
}

export interface GleaneryPersonIdentity {
  external_id: string;
  handle: string;
  id: Generated<Int8>;
  person_id: Int8 | null;
  provider: string;
}

export interface GleaneryProject {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  key: string;
  name: string;
}

export interface GleanerySourceItem {
  author_identity_id: Int8 | null;
  body: string | null;
  closed_at: Timestamp | null;
  connector_id: Int8;
  content_hash: Buffer;
  external_id: string;
  id: Generated<Int8>;
  kind: string;
  metadata: Generated<Json>;
  path: string | null;
  source_created_at: Timestamp | null;
  source_updated_at: Timestamp | null;
  state: string | null;
  synced_at: Generated<Timestamp>;
  title: string;
  url: string | null;
}

export interface GleaneryWorkItem {
  conversation_id: string | null;
  current: string;
  goal: string;
  id: Generated<Int8>;
  next: Generated<string[]>;
  project_id: Int8;
  source_key: string;
  status: string;
  title: string;
  updated_at: Timestamp;
}

export interface DB {
  "gleanery.connector": GleaneryConnector;
  "gleanery.conversation": GleaneryConversation;
  "gleanery.docs_exclude": GleaneryDocsExclude;
  "gleanery.knowledge": GleaneryKnowledge;
  "gleanery.knowledge_embedding": GleaneryKnowledgeEmbedding;
  "gleanery.knowledge_file": GleaneryKnowledgeFile;
  "gleanery.message": GleaneryMessage;
  "gleanery.message_embedding": GleaneryMessageEmbedding;
  "gleanery.message_file": GleaneryMessageFile;
  "gleanery.person": GleaneryPerson;
  "gleanery.person_identity": GleaneryPersonIdentity;
  "gleanery.project": GleaneryProject;
  "gleanery.source_item": GleanerySourceItem;
  "gleanery.work_item": GleaneryWorkItem;
}
